/*
 * Automatically generated file; DO NOT EDIT.
 */
#ifndef __ADSP_CONFIG_H
#define __ADSP_CONFIG_H

/* CFG_3RDPARTY_PROJECT is not set */
/* CFG_A2DP_OFFLOAD_SUPPORT is not set */
#define CFG_ADSP_A 0
#define CFG_ADSP_A_EX_DRAM_ADDRESS 0x3ffa0000
#define CFG_ADSP_A_EX_IRAM_ADDRESS 0x3ffc0000
#define CFG_ADSP_B 1
#define CFG_ADSP_B_EX_DRAM_ADDRESS 0x3ffd0000
#define CFG_ADSP_B_EX_IRAM_ADDRESS 0x3fff0000
#define CFG_ADSP_CORE_ID CFG_ADSP_B
#define CFG_ASSERT_SUPPORT
#define CFG_AUDIO_BASE_ADDRESS 0x42210000
#define CFG_AUDIO_BASE_ADDRESS_APVIEW 0x11210000
#define CFG_AUDIO_CONFIG_SIZE 0x2000
#define CFG_AUDIO_DATA_SIZE 0x18000
#define CFG_AUDIO_SUPPORT
/* CFG_BUS_MONITOR_SUPPORT is not set */
#define CFG_C2C_IPC_SUPPORT
#define CFG_CACHE_SUPPORT
#define CFG_DEBUG_COMMAND_SUPPORT
#define CFG_DMA_SUPPORT
#define CFG_FREERTOS_TRACE_SUPPORT
#define CFG_HIFI3_DRAM_ADDRESS 0x4ffb0000
#define CFG_HIFI3_DRAM_ADDRESS_APVIEW 0x10850000
#define CFG_HIFI3_DRAM_SIZE 0x8000
#define CFG_HIFI3_IRAM_ADDRESS 0x4ffe0000
#define CFG_HIFI3_IRAM_ADDRESS_APVIEW 0x10870000
#define CFG_HIFI3_IRAM_SIZE 0x9000
#define CFG_HIFI3_SRAM_ADDRESS 0x56700000
#define CFG_HIFI3_SRAM_SIZE 0x700000
#define CFG_IPC_SUPPORT
/* CFG_IRQ_MONITOR_SUPPORT is not set */
#define CFG_KERNEL_TIMESTAMP_SUPPORT
/* CFG_LEAUDIO_OFFLOAD_SUPPORT is not set */
#define CFG_LOGGER_SUPPORT
#define CFG_MAILBOX_SUPPORT
/* CFG_MCPS_PROF_SUPPORT is not set */
#define CFG_MPU_SUPPORT
#define CFG_MTK_AUDIODSP_SUPPORT
#define CFG_MTK_AUDIO_FRAMEWORK_SUPPORT
/* CFG_MTK_AUDIO_TUNNELING_SUPPORT is not set */
#define CFG_MTK_AURISYS_FRAMEWORK_SUPPORT
#define CFG_MTK_AURISYS_PHONE_CALL_SUPPORT
/* CFG_PERFORMANCE_MONITOR_SUPPORT is not set */
#define CFG_PHONE_CALL_CORE_ID CFG_ADSP_B
/* CFG_RAMDUMP_SUPPORT is not set */
/* CFG_RECOVERY_SUPPORT is not set */
#define CFG_SEMAPHORE_3WAY_SUPPORT
#define CFG_SEMAPHORE_SUPPORT
/* CFG_SUPPORT_AAC_VBR is not set */
#define CFG_SYSTEM_OFF_SUPPORT
#define CFG_TASK_MONITOR
#define CFG_TICKLESS_SUPPORT
/* CFG_TRAX_SUPPORT is not set */
/* CFG_UART_SUPPORT is not set */
/* CFG_USER_BUILD is not set */
/* CFG_UT_TESTSUITE_SUPPORT is not set */
#define CFG_VCORE_DVFS_SUPPORT
#define CFG_WAKELOCK_SUPPORT
#define CFG_WDT_SUPPORT
#define CFG_XGPT_SUPPORT

#endif /* __ADSP_CONFIG_H */
